[phases.setup]
nixPkgs = ["python313", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"

[variables]
PYTHONUNBUFFERED = "1"
HF_HOME = "/app/.cache/huggingface"
